#! /bin/bash /

# this script uses gum you can get it at https://github.com/charmbracelet/gumhttps://github.com/charmbracelet/gum


declare -A playlists

playlists["working"]="https://www.youtube.com/playlist?list=PL3AyWHvr_UThgm3gIBroTMRKEhV5zrQEl"
playlists["pog_stuff"]="https://www.youtube.com/playlist?list=PL3AyWHvr_UTgqqXii2AI4WF2s-WGQ2GlQ"

selected="$(gum choose "${!playlists[@]}")"

result=${playlists[$selected]}

conf=""

gum confirm "play" && conf="no"
if [[ -z "$conf" ]];  then
  gum style --foreground="1" "abording"
  exit 1
fi

gum style --foreground="2" "strting up $selected"

echo $(uta $result)
exit 0





